### ISSUE TITLE
High Fidelity Wireframes

### ISSUE THREAD

**Issue by Descent098** [glassthunder/TECHSTART#1]
# Goal
As a developer I want to get an idea of what the app will actually look like in practice

## Requirements
- [x] High fidelity design 
- [x] Basic HTML templates (don't need functionality, just to look as intended) [this might help](https://getbootstrap.com/)

**Comment by FelixVaughan** [comment]
Note: link to [lo-fi wirefreames](https://github.com/glassthunder/TECHSTART/tree/main/Planning/Wireframes_and_Diagrams)
